#!/bin/bash

### backup-shell
# Convenience script that copies a few shell config files into a folder here,
# so that I can push them into the Git repository.

cp -f ~/.zshrc ~/scripts/shell-config-backups/.zshrc
cp -f ~/.bashrc ~/scripts/shell-config-backups/.bashrc
cp -f ~/.bash_aliases ~/scripts/shell-config-backups/.bash_aliases
cp -f ~/.oh-my-zsh/themes/agnoster.zsh-theme ~/scripts/shell-config-backups/agnoster.zsh-theme
cp -f ~/.gitconfig ~/scripts/shell-config-backups/.gitconfig
cp -f ~/.gitignore ~/scripts/shell-config-backups/.gitignore
