#!/bin/bash

### dumping-ground
# Opens the ~/Projects/DumpingGround folder.
# If the current directory matches up to one in DumpingGround, open that
# subdirectory instead.

CURRENT_DIR=${PWD##*/}
DG_PATH="/home/adam/Projects/DumpingGround/"
DG_PROJECT_DIR=$DG_PATH$CURRENT_DIR

if [ -d "$DG_PROJECT_DIR" ]; then
    nautilus $DG_PROJECT_DIR
else
    nautilus $DG_PATH
fi
