#!/bin/bash

source virtualenvwrapper.sh

VENV_WORKDIR="$HOME/Projects"

# Accept the envname to be deleted as a parameter.
# Prepend "env-" if necessary.
NAME_TO_DELETE=$1
if [[ ${NAME_TO_DELETE:0:4} != "env-" ]]; then
    NAME_TO_DELETE="env-$NAME_TO_DELETE"
fi

# Confirm with the user.
delete_venv="n"
echo -n "Would you like to delete the virtual environment $NAME_TO_DELETE? (y/N) "
read delete_venv
if [[ $delete_venv == "y" || $delete_venv == "Y" ]]; then

    # If we're already in a virtual environment, deactivate it first.
    if [[ "$(type deactivate)" =~ "function" ]]; then
        echo "Deactivating existing virtualenv..."
        deactivate
    fi

    # Do the actual work.
    echo "Removing virtual env $NAME_TO_DELETE..."
    rmvirtualenv $NAME_TO_DELETE

    # Offer to delete the corresponding directory from the Projects folder.
    delete_dir="n"
    FOLDER_NAME=${NAME_TO_DELETE:4:200}
    echo -n "Would you like to delete the folder $VENV_WORKDIR/$FOLDER_NAME? (y/N) "
    read delete_dir
    if [[ $delete_dir == "y" || $delete_dir == "Y" ]]; then
        if [[ $PWD == $VENV_WORKDIR/$FOLDER_NAME ]]; then
            cd ..
        fi
        rm -rf "$VENV_WORKDIR/$FOLDER_NAME"
    fi

fi

unset VENV_WORKDIR
unset NAME_TO_DELETE
